### ISSUE TITLE
Design 1

### ISSUE THREAD

**Issue by andreszaidan** [mikehansonn/3704group3#1]
Finish design 1 submission by Thursday 31st of October.

**Comment by andreszaidan** [comment]
Finished Class diagram

**Comment by andreszaidan** [comment]
Started on ER diagram

**Comment by lealbert999** [comment]
Finished Data Tables

**Comment by mikehansonn** [comment]
ER Diagram Complete

**Comment by mikehansonn** [comment]
LucidChart reviewed and brushed up on
