### ISSUE TITLE
[Project] Final Presentation

### ISSUE THREAD

**Issue by mikehansonn** [mikehansonn/3704group3#26]
Grading rubrics:

For any group presenting on a certain day, all members should turn in a peer evaluation at the end of the class on that day to evaluate each other’s contributions and efforts. The score scale is 1-10, with 1 meaning the “really very bad”, and 10 meaning “very good”. One additional bonus point can be given to at most one member, for the person’s extraordinary work. Note that each person can only provide peer evaluations for the other members in the same group, but not for himself/herself or people in a different group. Please write down your name, when you evaluate the performance of your peers.
For any group attending the presentations given by other groups, only one member is supposed to turn in the evaluation on behalf of the whole group. The score scale is 1-10, with 1 meaning “really very bad”, and 10 meaning “very good”. One bonus point can be given to at most one group on each presentation day. The evaluation criteria: quality of the project, clearness of the presentation, and how well the presenters respond to answers during Q&A. Note that each group can only provide scores for other groups, but not for itself. Please put down your group number when you evaluate other groups.
The final grade of each group is the average of scores given by other groups. On top of that, the final grade of each group member is affected by the average score given by other members. Namely, if the final grade of a group is A (0<=A<=10) and the average score of peer evaluation for a group member is B (0<=B<=10), then the final grade of the group member is A * B/10. It means that to earn a high score, each member should work hard to ensure the quality of overall project, by (1) closely collaborating with peers and (2) diligently contributing efforts and high-quality artefacts for the tasks assigned to them.

**Comment by dnsmits** [comment]
final presentation complete with a Brief introduction of the project, The most appealing features in the system, Major challenges and the solutions, Lessons learnt, secret for success or summary and a Q&A section
